# Generated by Django 4.0.4 on 2022-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsRegistrationModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('photo', models.ImageField(default=False, upload_to='')),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Student_Registration_Details',
            },
        ),
    ]
