# Generated by Django 4.0.4 on 2022-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentsregistrationmodel',
            table='Student_Details',
        ),
    ]
