# Generated by Django 4.0.4 on 2022-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_alter_studentsregistrationmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('feedback_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Students_Feedback_Details',
            },
        ),
    ]
