# Generated by Django 4.0.4 on 2022-04-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostScholarshipModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_scholarship', models.CharField(max_length=155)),
                ('type_of_scheme', models.CharField(max_length=100, null=True)),
                ('name_of_scholarship', models.CharField(max_length=111)),
                ('amount', models.IntegerField(null=True)),
                ('eligibility', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=155)),
                ('documents_required', models.CharField(max_length=100, null=True)),
                ('last_date', models.DateField(null=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Post_Scholarship_Details',
            },
        ),
        migrations.CreateModel(
            name='ProviderRegistrationModel',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=155)),
                ('board_university', models.CharField(max_length=155)),
                ('pan_number', models.CharField(max_length=111)),
                ('hod_institute', models.CharField(max_length=111)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('firm_registration', models.ImageField(default=False, upload_to='')),
                ('photo', models.ImageField(default=False, upload_to='')),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Scholarship_Provider_Details',
            },
        ),
    ]
