# Generated by Django 4.0.4 on 2022-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipprovidersapp', '0002_alter_providerregistration_pan_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerregistration',
            name='pan_number',
            field=models.CharField(max_length=111),
        ),
    ]
