# Generated by Django 4.0.4 on 2022-04-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipprovidersapp', '0004_rename_providerregistration_providerregistrationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerregistrationmodel',
            old_name='reg_id',
            new_name='provider_id',
        ),
    ]
