# Generated by Django 4.0.4 on 2022-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipprovidersapp', '0005_rename_reg_id_providerregistrationmodel_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostScholarshipModel',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_scholarship', models.CharField(max_length=155)),
                ('name_of_scholarship', models.CharField(max_length=111)),
                ('amount', models.IntegerField(null=True)),
                ('eligibility', models.CharField(max_length=55)),
                ('description', models.TextField(max_length=155)),
                ('last_date', models.DateField(null=True)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Post_Scholarship_Details',
            },
        ),
    ]
