# Generated by Django 4.0.4 on 2022-04-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarshipprovidersapp', '0006_postscholarshipmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postscholarshipmodel',
            name='documents_required',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postscholarshipmodel',
            name='type_of_scheme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
